# Generated by Django 3.1 on 2021-10-20 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('passworld', models.CharField(default='', max_length=100, verbose_name='Passworld')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration data')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
