# Generated by Django 3.1 on 2021-10-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default='', max_length=8, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=100, verbose_name='Product')),
                ('quantity', models.CharField(default='', max_length=100, verbose_name='Quantity')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.users', verbose_name='Users')),
            ],
        ),
    ]
